"""added temporary price field to advertisement model

Revision ID: 00b49ff4b2c0
Revises: f5b6b0be9967
Create Date: 2025-11-22 13:44:56.385739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b49ff4b2c0'
down_revision: Union[str, None] = 'f5b6b0be9967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('temporary_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'temporary_price')
    # ### end Alembic commands ###
