"""added 'for_base_channel' field

Revision ID: 040033acdd28
Revises: fedaf791d4b7
Create Date: 2025-07-21 15:22:01.201766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040033acdd28'
down_revision: Union[str, None] = 'fedaf791d4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('for_base_channel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'for_base_channel')
    # ### end Alembic commands ###
