"""added 'added_by' field to user model

Revision ID: 05449d54a95b
Revises: ecb1fc4e291b
Create Date: 2024-12-29 19:47:32.910793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05449d54a95b'
down_revision: Union[str, None] = 'ecb1fc4e291b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('added_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'added_by')
    # ### end Alembic commands ###
