"""added is_moderated to advertisement model

Revision ID: 0866fce9e7ce
Revises: f69b43d0385f
Create Date: 2024-12-12 16:51:48.099149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0866fce9e7ce'
down_revision: Union[str, None] = 'f69b43d0385f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('is_moderated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'is_moderated')
    # ### end Alembic commands ###
