"""added fixes in relations

Revision ID: 119e2347a525
Revises: 2939fb0af83f
Create Date: 2024-12-01 01:35:33.253184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119e2347a525'
down_revision: Union[str, None] = '2939fb0af83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('advertisements', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('advertisements', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('advertisements_district_fkey', 'advertisements', type_='foreignkey')
    op.drop_constraint('advertisements_user_fkey', 'advertisements', type_='foreignkey')
    op.drop_constraint('advertisements_category_fkey', 'advertisements', type_='foreignkey')
    op.create_foreign_key(None, 'advertisements', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'advertisements', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'advertisements', 'users', ['user_id'], ['id'])
    op.drop_column('advertisements', 'district')
    op.drop_column('advertisements', 'user')
    op.drop_column('advertisements', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('advertisements', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('advertisements', sa.Column('district', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.create_foreign_key('advertisements_category_fkey', 'advertisements', 'categories', ['category'], ['id'])
    op.create_foreign_key('advertisements_user_fkey', 'advertisements', 'users', ['user'], ['id'])
    op.create_foreign_key('advertisements_district_fkey', 'advertisements', 'districts', ['district'], ['id'], ondelete='SET NULL')
    op.drop_column('advertisements', 'user_id')
    op.drop_column('advertisements', 'category_id')
    op.drop_column('advertisements', 'district_id')
    # ### end Alembic commands ###
