"""added rooms_quantity to advetrisement table

Revision ID: 222ae2e67493
Revises: 05449d54a95b
Create Date: 2025-01-15 00:15:18.634045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222ae2e67493'
down_revision: Union[str, None] = '05449d54a95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('rooms_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'rooms_quantity')
    # ### end Alembic commands ###
