"""added reminder_time for advertisement

Revision ID: 22eeea7957b8
Revises: efb5d4c5f3f0
Create Date: 2025-10-17 12:12:15.526748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22eeea7957b8'
down_revision: Union[str, None] = 'efb5d4c5f3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('reminder_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'reminder_time')
    # ### end Alembic commands ###
