"""added str to image hash

Revision ID: 27f0d2b035e0
Revises: 63985b7ef423
Create Date: 2025-09-23 11:10:32.557071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f0d2b035e0'
down_revision: Union[str, None] = '63985b7ef423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisement_images', 'image_hash',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisement_images', 'image_hash',
               existing_type=sa.String(length=16),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
