"""fixed wrong column names

Revision ID: 2939fb0af83f
Revises: e77138746445
Create Date: 2024-11-28 20:23:59.228867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2939fb0af83f'
down_revision: Union[str, None] = 'e77138746445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('operation_type', postgresql.ENUM('BUY', 'RENT', name='operationtype'), nullable=False))
    op.drop_column('advertisements', 'opretion_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('opretion_type', postgresql.ENUM('BUY', 'RENT', name='operationtype'), autoincrement=False, nullable=False))
    op.drop_column('advertisements', 'operation_type')
    # ### end Alembic commands ###
