"""deleted fields

Revision ID: 29bb424ad5dc
Revises: e7e876a9f15b
Create Date: 2024-11-24 21:33:21.060513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bb424ad5dc'
down_revision: Union[str, None] = 'e7e876a9f15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name_uz')
    op.drop_column('districts', 'name_uz')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('name_uz', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('name_uz', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
