"""deleted advertisement duplicated model

Revision ID: 2e8b1e1c9586
Revises: 5135f0edf537
Create Date: 2025-10-02 12:46:56.579059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8b1e1c9586'
down_revision: Union[str, None] = '5135f0edf537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisement_duplicateds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement_duplicateds',
    sa.Column('advertisement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_to_send', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], name='advertisement_duplicateds_advertisement_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='advertisement_duplicateds_pkey')
    )
    # ### end Alembic commands ###
