"""edited fields

Revision ID: 3426dfee3319
Revises: 852dc0f1148b
Create Date: 2024-12-07 01:58:04.615244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3426dfee3319'
down_revision: Union[str, None] = '852dc0f1148b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('advertisements_user_id_fkey', 'advertisements', type_='foreignkey')
    op.create_foreign_key(None, 'advertisements', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('fullname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fullname')
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.create_foreign_key('advertisements_user_id_fkey', 'advertisements', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
