"""added quadrature field

Revision ID: 35fb20a91c4f
Revises: b7cbe6ce4935
Create Date: 2025-01-16 18:50:03.036815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35fb20a91c4f'
down_revision: Union[str, None] = 'b7cbe6ce4935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('quadrature', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'quadrature')
    # ### end Alembic commands ###
