"""added image hash

Revision ID: 3d1a65932bde
Revises: 88db1701a0cf
Create Date: 2025-09-22 16:14:33.522945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1a65932bde'
down_revision: Union[str, None] = '88db1701a0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement_images', sa.Column('image_hash', sa.Integer(), nullable=True))
    # op.drop_constraint('advertisements_unique_id_key', 'advertisements', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('advertisements_unique_id_key', 'advertisements', ['unique_id'])
    op.drop_column('advertisement_images', 'image_hash')
    # ### end Alembic commands ###
