"""added new field to duplicated advertisement model

Revision ID: 5135f0edf537
Revises: e2e15d9bf9e7
Create Date: 2025-10-02 12:34:42.367532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5135f0edf537'
down_revision: Union[str, None] = 'e2e15d9bf9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement_duplicateds', sa.Column('is_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisement_duplicateds', 'is_sent')
    # ### end Alembic commands ###
