"""added uz fields in model

Revision ID: 5320db3bbaf1
Revises: f879844a46b7
Create Date: 2024-12-02 02:06:35.657925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5320db3bbaf1'
down_revision: Union[str, None] = 'f879844a46b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('name_uz', sa.String(), nullable=True))
    op.add_column('advertisements', sa.Column('description_uz', sa.String(), nullable=True))
    op.add_column('advertisements', sa.Column('address_uz', sa.String(), nullable=True))
    op.drop_column('advertisements', 'is_moderated')
    op.add_column('categories', sa.Column('name_uz', sa.String(), nullable=True))
    op.add_column('districts', sa.Column('name_uz', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('districts', 'name_uz')
    op.drop_column('categories', 'name_uz')
    op.add_column('advertisements', sa.Column('is_moderated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('advertisements', 'address_uz')
    op.drop_column('advertisements', 'description_uz')
    op.drop_column('advertisements', 'name_uz')
    # ### end Alembic commands ###
