"""added fixes

Revision ID: 6e39067de97a
Revises: 2e8b1e1c9586
Create Date: 2025-10-02 12:59:49.834831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e39067de97a'
down_revision: Union[str, None] = '2e8b1e1c9586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement_duplicateds',
    sa.Column('advertisement_id', sa.Integer(), nullable=True),
    sa.Column('duplicated_advertisement_id', sa.Integer(), nullable=False),
    sa.Column('time_to_send', sa.DateTime(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicated_advertisement_id'], ['advertisements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisement_duplicateds')
    # ### end Alembic commands ###
