"""removed slug from advertisement

Revision ID: 6fbeaf616adb
Revises: 62e37dc88f81
Create Date: 2024-12-16 20:40:59.686217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbeaf616adb'
down_revision: Union[str, None] = '62e37dc88f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_advertisements_slug', table_name='advertisements')
    op.drop_column('advertisements', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_advertisements_slug', 'advertisements', ['slug'], unique=True)
    # ### end Alembic commands ###
