"""added fixes for unique code

Revision ID: 7ac50b02a8e7
Revises: 27f0d2b035e0
Create Date: 2025-09-24 13:20:03.499511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac50b02a8e7'
down_revision: Union[str, None] = '27f0d2b035e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
