"""added owner_phone_number

Revision ID: 8303fb1722eb
Revises: a98e3dce5a22
Create Date: 2025-01-16 19:51:21.645074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8303fb1722eb'
down_revision: Union[str, None] = 'a98e3dce5a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('owner_phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'owner_phone_number')
    # ### end Alembic commands ###
