"""added preview field

Revision ID: 852dc0f1148b
Revises: 4af01dbb04aa
Create Date: 2024-12-02 22:21:27.482093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852dc0f1148b'
down_revision: Union[str, None] = '4af01dbb04aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('preview', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'preview')
    # ### end Alembic commands ###
