"""removed is_studio from advertisement

Revision ID: 88db1701a0cf
Revises: 040033acdd28
Create Date: 2025-08-27 11:35:25.660781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88db1701a0cf'
down_revision: Union[str, None] = '040033acdd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'is_studio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('is_studio', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
