"""added nullable for user model

Revision ID: 8ac7cedb8ee6
Revises: 29bb424ad5dc
Create Date: 2024-11-25 11:25:42.703618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac7cedb8ee6'
down_revision: Union[str, None] = '29bb424ad5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
