"""added proeprty type uz

Revision ID: 9951f69d6403
Revises: 5320db3bbaf1
Create Date: 2024-12-02 10:57:38.005186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9951f69d6403"
down_revision: Union[str, None] = "5320db3bbaf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE propertytypeuz AS ENUM('NEW', 'OLD')")
    op.add_column(
        "advertisements",
        sa.Column(
            "property_type_uz",
            postgresql.ENUM("NEW", "OLD", name="propertytypeuz"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("advertisements", "property_type_uz")
    # ### end Alembic commands ###
