"""added new field for advertisement image

Revision ID: 9d1f85fde39b
Revises: cce268c5635e
Create Date: 2024-12-01 17:00:33.031589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1f85fde39b'
down_revision: Union[str, None] = 'cce268c5635e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement_images', sa.Column('tg_image_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisement_images', 'tg_image_hash')
    # ### end Alembic commands ###
