"""removed updated and temporary prices from advertisement model

Revision ID: a1ed3341b10c
Revises: 00b49ff4b2c0
Create Date: 2025-11-22 20:57:56.704359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ed3341b10c'
down_revision: Union[str, None] = '00b49ff4b2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'temporary_price')
    op.drop_column('advertisements', 'updated_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('updated_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('advertisements', sa.Column('temporary_price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
