"""added operation type uz

Revision ID: c4f9cec18d33
Revises: 9951f69d6403
Create Date: 2024-12-02 11:02:44.202100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4f9cec18d33"
down_revision: Union[str, None] = "9951f69d6403"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE operationtypeuz AS ENUM('BUY', 'RENT')")
    op.add_column(
        "advertisements",
        sa.Column(
            "operation_type_uz",
            postgresql.ENUM("BUY", "RENT", name="operationtypeuz"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("advertisements", "operation_type_uz")
    # ### end Alembic commands ###
