"""added old and new price field to advertisement model

Revision ID: c7c7a25853cc
Revises: a1ed3341b10c
Create Date: 2025-11-22 21:10:14.022643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c7a25853cc'
down_revision: Union[str, None] = 'a1ed3341b10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('new_price', sa.Integer(), nullable=True))
    op.add_column('advertisements', sa.Column('old_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'old_price')
    op.drop_column('advertisements', 'new_price')
    # ### end Alembic commands ###
