"""added is_reminded field

Revision ID: d077b712a58e
Revises: 22eeea7957b8
Create Date: 2025-10-17 13:36:31.864865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd077b712a58e'
down_revision: Union[str, None] = '22eeea7957b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('is_reminded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'is_reminded')
    # ### end Alembic commands ###
