"""added model for duplicated advertisements

Revision ID: e2e15d9bf9e7
Revises: 7ac50b02a8e7
Create Date: 2025-10-02 10:49:51.199946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e15d9bf9e7'
down_revision: Union[str, None] = '7ac50b02a8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement_duplicateds',
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('time_to_send', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisement_duplicateds')
    # ### end Alembic commands ###
