"""added models

Revision ID: e7e876a9f15b
Revises: fed01f46d11b
Create Date: 2024-11-24 21:21:09.905645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7e876a9f15b'
down_revision: Union[str, None] = 'fed01f46d11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('lastname', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('tg_username', sa.String(), nullable=False),
    sa.Column('tg_chat_id', sa.BIGINT(), nullable=False),
    sa.Column('role', postgresql.ENUM('REALTOR', 'GROUP_DIRECTOR', name='userrole'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('tg_username')
    )
    op.create_table('advertisements',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('house_quadrature_from', sa.Integer(), nullable=False),
    sa.Column('house_quadrature_to', sa.Integer(), nullable=False),
    sa.Column('creation_year', sa.Integer(), nullable=False),
    sa.Column('is_moderated', sa.Boolean(), nullable=False),
    sa.Column('property_type', postgresql.ENUM('NEW', 'OLD', name='propertytype'), nullable=False),
    sa.Column('opretion_type', postgresql.ENUM('BUY', 'RENT', name='operationtype'), nullable=False),
    sa.Column('repair_type', postgresql.ENUM('WITH', 'WITHOUT', 'DESIGNED', 'ROUGH', 'PRE_FINISHED', name='repairtype'), nullable=False),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('rooms_qty_from', sa.Integer(), nullable=False),
    sa.Column('rooms_qty_to', sa.Integer(), nullable=False),
    sa.Column('quadrature_from', sa.Integer(), nullable=False),
    sa.Column('quadrature_to', sa.Integer(), nullable=False),
    sa.Column('floor_from', sa.Integer(), nullable=False),
    sa.Column('floor_to', sa.Integer(), nullable=False),
    sa.Column('is_studio', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['district'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisements_name'), 'advertisements', ['name'], unique=False)
    op.create_index(op.f('ix_advertisements_slug'), 'advertisements', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisements_slug'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_name'), table_name='advertisements')
    op.drop_table('advertisements')
    op.drop_table('users')
    # ### end Alembic commands ###
