"""added advertisement queue model

Revision ID: efb5d4c5f3f0
Revises: 4b0ef7a74d7b
Create Date: 2025-10-05 20:42:51.896261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb5d4c5f3f0'
down_revision: Union[str, None] = '4b0ef7a74d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement_queues',
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('time_to_send', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisement_queues')
    # ### end Alembic commands ###
