"""added fixes

Revision ID: fedaf791d4b7
Revises: 080cbb3653bd
Create Date: 2025-02-26 11:52:14.946595

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fedaf791d4b7"
down_revision: Union[str, None] = "080cbb3653bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('advertisements', 'house_quadrature_from',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    # op.alter_column('advertisements', 'house_quadrature_to',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)\
    op.execute(
        "ALTER TABLE advertisements ALTER COLUMN house_quadrature_from TYPE INTEGER USING house_quadrature_from::integer"
    )
    op.execute(
        "ALTER TABLE advertisements ALTER COLUMN house_quadrature_to TYPE INTEGER USING house_quadrature_to::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "advertisements",
        "house_quadrature_to",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "advertisements",
        "house_quadrature_from",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
