"""added unique_id field to advertisement

Revision ID: fef741438a1d
Revises: 5135ff3911af
Create Date: 2024-12-29 14:11:07.101865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef741438a1d'
down_revision: Union[str, None] = '5135ff3911af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('unique_id', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'unique_id')
    # ### end Alembic commands ###
